# Base image
FROM node:20

# Create app directory inside container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the backend code
COPY . .

# Expose the backend port (e.g., 5000)
EXPOSE 5000

# Start the server
CMD ["npm", "start"]
